export const TITLE_DAILY_RECOMMENDATION = "A ne pas manquer aujourd'hui !";
export const TITLE_POPULAR_RELEASE = "Dernières sorties populaires !";
export const SEE_ALL = "Voir tout";
export const TITLES = "titres";
export const TITLE = "titre";
export const ADD_TO_LIBRARY = "Ajouté dans la bibliothèque";
export const DELETE_TO_LIBRARY = "Supprimé de la bibliothèque";
export const ARRAY_HEADER_FIRST_COLUMN = "#";
export const ARRAY_HEADER_COLUMN_TITLE = "Titre";
